version: "3.9"

services:
  server:
    build: ./server
    container_name: task-manager-server
    ports:
      - "5001:5001"
    environment:
      - MONGODB_URI=mongodb://mongo:27017/todo-app
      - NODE_ENV=development
    depends_on:
      - mongo
  
  client:
    build: ./client
    container_name: task-manager-client
    ports:
      - "3000:80"
    depends_on:
      - server


  mongo:
    image: mongo:latest
    container_name: task-manager-mongo
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db

volumes:
  mongo-data: