name: Client Cl

on:
  push:
    branches: [ main ]
    paths:
      - 'client/*'
      - '.github/workflows/client.yml'
  pull_request:
    branches: [ main ]
    paths:
      - 'client/*'
      - '.github/workflows/client.yml'